<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi lista de peliculas</title>
    <style>
        h1{
			text-align:center;
		}
        img{
            width:300px;
        }
    </style>
</head>
<body>
    <h1>Mi lista de peliculas</h1>

    <a href="index.php">Inicio</a><br><br>

    <?php
        echo '<p>'.$movie->getTitle().'</p>';
        echo '<img src="views/'.$movie->getImage().'"/>';
        echo '<p>Estrenado en '.$movie->getYear().'</p>';
        echo $movie->getLikes().' Likes <a href="index.php?like='.$movie->getId().'">LIKE</a>';
    ?>
</body>
</html>