<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login view</title>
</head>
<body>
    <h2>Login</h2>
    <form action="index.php?login" method="POST">
        <input type="text" name="user" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" name="logeo" value="Login">
    </form>

    <h2>Registro</h2>
    <form action="index.php?login" method="POST">
        <input type="text" name="user" placeholder="Nombre de usuario">
        <input type="password" name="password" placeholder="Contraseña">
        <input type="password" name="password2" placeholder="Repite la contraseña">
        <input type="email" name="email" placeholder="Correo electronico">
        <input type="submit" name="registro" value="Registro">
    </form>

</body>
</html>