<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MainView</title>
</head>
<body>
    <?php
    if($_SESSION['user']->rol == 0)
        echo '<p><a href="index.php?login">Login</a></p>';
    else
        echo '<p>Hola '.$_SESSION['user']->name.' - <a href="index.php?login&logout">Logout</a></p>';
    ?>
    
    <?php
    if($_SESSION['user']->rol > 0){
    ?>
    <h2>Registrar pokemon</h2>
    <form action="index.php?pokemon" method="POST">
        <input type="text" name="name" placeholder="name">
        <input type="text" name="type" placeholder="type">
        <input type="text" name="image" placeholder="image">
        <input type="submit" name="addPokemon" value="Add">
    </form>

    <h2>Lista de mis pokemon</h2>
    <?php
        foreach($_SESSION['user']->pokedex as $pokemon){
            echo '<p>'.$pokemon.'</p>';//al tener el toString no hace falta llamar a name
        }
    

        echo '<h2>Registrar equipo</h2>';

        $pokedex = $_SESSION['user']->pokedex;//Para seleccionar el nombre de TUS pokemons
        echo '<form action="index.php?pokemon" method="POST">
            <input type="text" name="name" placeholder="nombre del equipo">';
            echo '<select name="idP1">';
            foreach($pokedex as $pokemon){
                echo '<option value="'.$pokemon->id.'">'.$pokemon.'</option>';//al tener el toString no hace falta llamar a name
            }
            echo '</select>';
            echo '<select name="idP2">';
            foreach($pokedex as $pokemon){
                echo '<option value="'.$pokemon->id.'">'.$pokemon.'</option>';//al tener el toString no hace falta llamar a name
            }
            echo '</select>';
            echo '<select name="idP3">';
            foreach($pokedex as $pokemon){
                echo '<option value="'.$pokemon->id.'">'.$pokemon.'</option>';//al tener el toString no hace falta llamar a name
            }
            echo '</select>';
            echo '<select name="idP4">';
            foreach($pokedex as $pokemon){
                echo '<option value="'.$pokemon->id.'">'.$pokemon.'</option>';//al tener el toString no hace falta llamar a name
            }
            echo '</select>';
            echo '<select name="idP5">';
            foreach($pokedex as $pokemon){
                echo '<option value="'.$pokemon->id.'">'.$pokemon.'</option>';//al tener el toString no hace falta llamar a name
            }
            echo '</select>';
        echo '<input type="submit" name="addTeam" value="Crear equipo">
        </form>';


        echo '<h2>Lista de mis equipos</h2>';
        foreach($_SESSION['user']->teams as $team){
            echo $team.'<br>';
        }

    if($_SESSION['user']->rol == 2){
        echo '<h2>Stats</h2>';
        echo 'Master Creator: '.$masterCreator->name.'<br>';
        echo 'Master Team: '.$masterTeam->name.'<br>';
    }

    
    ?>

    <h2>POKEMON ENCONTRADOS</h2>
    <?php
    foreach($otherPokemons as $pokemon){//tbn se puede usar $pokemons para mostrar todos,
        //aunque esten en la pokedex, no dejaria insertarse ya que con el mismo idUser e idPokemon, al ser primary keys no deja
        echo '<p>'.$pokemon.'<a href="index.php?pokemon&add='.$pokemon->id.'">Añadir a mi pokedex</a></p>';
    }
    
    }else{//si no esta logueaddo
        echo '<h2>POKEMON ENCONTRADOS</h2>';
        foreach($pokemons as $pokemon){
            echo '<p>'.$pokemon.'</p>';
        }
    }
    ?>

</body>
</html>