<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="styles/styles.css"/>
    <title>examJuande</title>
</head>

<body>
    <?php require_once("views/_header.php"); ?>
    <section class="container-fluid container-md">
        <h2>POKEMON'S LIST</h2>
        <?php
        foreach($listPokemon as $pokemon){
            echo '<div>';
            echo '<img src="img/'.$pokemon->img.'" alt="'.$pokemon->name.'"/>';
            echo '<p>Name: '.$pokemon->name.' - Type: '.$pokemon->type.'</p>';
            echo '</div>';
        }
        ?>
    </section>

    <script src="styles/bootstrap/js/libreriaJquery.js"></script>
    <script src="styles/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>