<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="styles/styles.css"/>
    <title>examJuande</title>
</head>

<body>
    <?php require_once("views/_header.php"); ?>
    <section class="container-fluid container-md">
        <h2 class="text-center">Register</h2>
        <form action="index.php?register" method="POST">
            <div class="form-group">
                <label for="name">Name: </label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="password2">Repeat your password: </label>
                <input type="password" class="form-control" id="password2" name="password2" required>
            </div>
            <div class="form-group d-flex justify-content-center">
                <input type="submit" class="btn btn-success" name="register" value="Register">
            </div>
        </form>
    </section>

    <script src="styles/bootstrap/js/libreriaJquery.js"></script>
    <script src="styles/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>