<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MainView</title>
</head>
<body>
    <a href="index.php?login&logout">Logout</a><br><br>
    <?php
    echo 'Hola '.$_SESSION['user']->name;
    ?>
    <h1>Usuarios de la bd</h1>
    <ul>
    <?php
    foreach($users as $user){
        echo '<li>'.$user->name.'</li>';
    }
    ?>
    </ul>

    <h2>No amigos</h2>

    <?php
    foreach($_SESSION['user']->notfriends as $friend){
        echo $friend->name;
        echo " (".count($friend->friends)." amigos)";
        echo " - <a href='index.php?user&addFriend=".$friend->id."'>Solicitar amistad</a><br>";
    }
    ?>
    
    <h2>Amigos</h2>

    <?php
    if($friends = $_SESSION['user']->friends)
        foreach($friends as $friend){
            echo $friend->name;
            echo " - <a href='index.php?user&delFriend=".$friend->id."'>Quitar amistad</a><br>";
        }
    else
        echo "No tienes amigos aun";
    ?>

</body>
</html>