<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit User</title>
</head>
<body>
    <?php echo '<form action="index.php?admin&save='.$user->getId().'" method="POST">' ;?>
        <?php
        echo '<input type="text" name="user" value="'.$user->getName().'"/>';
        echo '<input type="email" name="email" value="'.$user->getEmail().'"/>';
        ?>
        <input type="submit" value="Actualizar"/>
    </form>
</body>
</html>