<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="styles/css.css">
    <title>Admin</title>
</head>
<body>
    <header>
    <?php
    if(isset($_SESSION['user'])){
        echo "<a href='index.php?logout'>Log out</a>";
    }
    ?>
    </header>
    <section id="main">
        <section class="adminView">
        <?php
        foreach(MainRepository::getUsers() as $user){
        ?>
        <div class="user">
            <form action="index.php" method="POST">
                <div>
                    <div class="form-group">
                        <label for="name">Name: </label>
                        <?php echo '<input type="text" id="name" name="name" value="'.$user->getName().'">';?>
                    </div>
                    <div class="form-group">
                        <label for="email">Email: </label>
                        <?php echo '<input type="email" id="email" name="email" value="'.$user->getEmail().'">';?>
                    </div>
                    <div class="form-group">
                        <label for="rol">Rol: </label>
                        <?php echo '<input type="number" id="rol" name="rol" min="1" max="2" value="'.$user->getRol().'">';?>
                    </div>
                    <?php echo '<input type="hidden" name="id" value="'.$user->getId().'">';?>
                </div>
                <input type="submit" name="update" value="Update">
            </form>
        </div>
        <?php } ?>
        </section>
    </section>
</body>
</html>