<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="styles/css.css">
    <title>Login</title>
</head>
<body>
    <section id="main">
        <section class="loginView">
        <form action="index.php?login" method="POST">
            <label for="name">Username:</label>
            <input type="text" id="name" name="name"><br>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password"><br>

            <input type="submit" name="login" value="Login">
        </form>
        </section>
    </section>
</body>
</html>