<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="styles/css.css">
    <title>Main</title>
</head>
<body>
    <header>
    <?php
    if(isset($_SESSION['user'])){
        echo "<a href='index.php?logout'>Log out</a>";
    }else{
    ?>
        <a href="index.php?login">Log in</a>
        <a href="index.php?register">Register</a>
    <?php
    }
    ?>
    </header>
    <section id="main">
        
    </section>
</body>
</html>