<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="styles/css.css">
    <title>Register</title>
</head>
<body>
    <section id="main">
        <section class="registerView">
        <form action="index.php?register" method="POST">
            <label for="name">Username:</label>
            <input type="text" id="name" name="name"><br>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password"><br>

            <label for="password2">Repeat password:</label>
            <input type="password" id="password2" name="password2"><br>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email"><br>

            <input type="submit" name="register" value="Register">
        </form>
        </section>
    </section>
</body>
</html>