<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="styles/css.css">
    <title>Hello</title>
</head>
<body>
    <header>
    <?php
    if(isset($_SESSION['user'])){
        echo "<a href='index.php?logout'>Log out</a>";
    }
    ?>
    </header>

    <section id="main">
        <section class="userView">
        <?php
        if(isset($_SESSION['user'])){
            echo "<h2>Hello ".$_SESSION['user']->getName()."</h2>";       
        }
        ?>
        </section>
    </section>
</body>
</html>